""" Transcations """
from .base import BaseModel

class Transaction(BaseModel):
    def __init__(self, transactions):
        super().__init__([
            {
                'filing_nid': t['filingNid'], # This will be used to join to filings
                'Rec_Type': (tran := t['transaction'])['recType'],
                'Tran_ID': tran['tranId'],
                'Entity_CD': tran['entityCd'],
                'Tran_NamL': tran['tranNamL'],
                'Tran_NamF': tran['tranNamF'],
                'Tran_NamT': tran['tranNamT'],
                'Tran_NamS': tran['tranNamS'],
                'Tran_Adr1': tran['tranAdr1'],
                'Tran_Adr2': tran['tranAdr2'],
                'Tran_State': tran['tranST'],
                'Tran_Zip4': tran['tranZip4'],
                'Tran_Emp': tran['tranEmp'],
                'Tran_Occ': tran['tranOcc'],
                'Tran_Self': tran['tranSelf'],
                'Tran_Type': tran['tranType'],
                'Tran_Date': tran['tranDate'],
                'Tran_Date1': tran['tranDate1'],
                'Tran_Amt1': tran['tranAmt1'],
                'Tran_Amt2': tran['tranAmt2'],
                'Tran_Dscr': tran['tranDscr'],
                'Cmte_ID': tran['cmteId'],
                'Tres_NamL': tran['tresNamL'],
                'Tres_NamF': tran['tresNamF'],
                'Tres_NamT': tran['tresNamT'],
                'Tres_NamS': tran['tresNamS'],
                'Tres_Adr1': tran['tresAdr1'],
                'Tres_Adr2': tran['tresAdr2'],
                'Tres_City': tran['tresCity'],
                'Tres_State': tran['tresST'],
                'Tres_Zip': tran['tresZip4'],
                'Intr_NamL': tran['intrNamL'],
                'Intr_NamF': tran['intrNamF'],
                'Intr_NamT': tran['intrNamT'],
                'Intr_NamS': tran['intrNamS'],
                'Intr_Adr1': tran['intrAdr1'],
                'Intr_Adr2': tran['intrAdr2'],
                'Intr_City': tran['intrCity'],
                'Intr_State': tran['intrST'],
                'Intr_Zip': tran['intrZip4'],
                'Intr_Emp': tran['intrEmp'],
                'Intr_Occ': tran['intrOcc'],
                'Intr_Self': tran['intrSelf'],
                'Cand_NamL': tran['candNamL'],
                'Cand_NamF': tran['candNamF'],
                'Cand_NamT': tran['candNamT'],
                'Cand_NamS': tran['candNamS'],
                'tblDetlTran_Office_Cd': tran['officeCd'],
                'tblDetlTran_Offic_Dscr': tran['officeDscr'],
                'Juris_Cd': tran['jurisCd'],
                'Juris_Dscr': tran['jurisDscr'],
                'Dist_No': tran['distNo'],
                'Off_S_H_Cd': tran['offSHCd'],
                'Bal_Name': tran['balName'],
                'Bal_Num': tran['balNum'],
                'Bal_Juris': tran['balJuris'],
                'Sup_Opp_Cd': tran['supOppCd'],
                'Memo_Code': tran['memoCode'],
                'Memo_RefNo': tran['memoRefNo'],
                'BakRef_TID': tran['bakRefTID'],
                'XRef_SchNm': tran['xrefSchNm'],
                'XRef_Match': tran['xrefMatch'],
                'Loan_Rate': tran['loanRate'],
                'Int_CmteId': tran['intCmteId']
            } for t in transactions
        ])

        self._dtypes = 'string'
